name: Add or update Terraform backend
description: Service interface for adding or updating a Terraform backend in the Open Source Infrastructure (as Code) organization.
title: Add or update Terraform backend
labels:
  - enhancement
  - good first issue

body:
  - type: markdown
    attributes:
      value: |
        Please fill out the following details to add or update a Terraform backend in the Open Source Infrastructure (as Code) organization.

  - type: input
    id: email-address
    attributes:
      label: "Email address:"
      description: How can we get in touch with you if we need more info?
      placeholder: email@example.com
    validations:
      required: true

  - type: input
    id: google-folder-path
    attributes:
      label: "Google folder path:"
      description: The path of the Google folder to create or update.
      placeholder: Platform - Kubernetes Engine/Autopilot
    validations:
      required: true

  - type: input
    id: github-repository
    attributes:
      label: "Repository name(s):"
      description: The name or names of the repositories to add that are allowed to create resources in the above Google folder path using OIDC authentication.
      placeholder: google-cloud-kubernetes-engine-autopilot, ...
    validations:
      required: true

  - type: textarea
    id: comments
    attributes:
      label: "Additional comments:"
      description: Anything else you'd like to add that would help us understand your request better?
    validations:
      required: false
